---
title: "Classify Data"
execute:
  echo: true
  code-tools: true
  code-fold: show
---

## Setup

### Packages

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ecmwfr)
  library(tidync)
  library(data.table)
  library(sf)
  library(arrow)
  library(units)

  library(gt)
  #library(gtExtras)
  #library(htmltools)

  library(RColorBrewer)
  library(viridis)
  library(scales) # for cut_number
  library(rnaturalearth)
})
```

### Climate Periods

```{r climate-periods}

# Climatological Standard Reference Period Normals
crp_beg <- 1961
crp_end <- 1990
crp_lbl <- paste("CRP ", crp_beg, "-", crp_end, sep = "")

# Climatological Period Average
cpa_beg <- 2011
cpa_end <- 2020
cpa_lbl <- paste("CPA ", cpa_beg, "-", cpa_end, sep = "")
```

### Paths

```{r paths}
dir_transform <- "_data/2-transform/"
dir_classify <- "_data/classify/"
```

```{r figures-output}
# Centralize figures created by chunks in this doc
knitr::opts_chunk$set(fig.path = "_figures/classify-")
```

### Dictionaries

```{r ktc-dictionary}

ktc_zone <- c(
    "Ar",
    "Aw",
    "BW",
    "BS",
    "Cs",
    "Cf",
    "Do",
    "Dc",
    "E",
    "Ft",
    "Fi"
  )

ktc_label <- c(
    "Ar: Tropical Wet",
    "Aw: Tropical Wet & Dry",
    "BW: Desert",
    "BS: Steppe",
    "Cs: Mediterranean",
    "Cf: Subtropical",
    "Do: Temperate Oceanic",
    "Dc: Temperate Continental",
    "E:  Sub-Arctic",
    "Ft: Polar Tundra",
    "Fi: Polar Ice Cap"
  )

ktc_dict  <- data.frame(zone= ktc_zone, label=ktc_label)
```

```{r kcc-dictionary}

kcc_zone <- c(
    "Af",
    "Am",
    "As",
    "Aw",
    "BSh",
    "BSk",
    "BWh",
    "BWk",
    "Cfa",
    "Cfb",
    "Cfc",
    "Csa",
    "Csb",
    "Csc",
    "Cwa",
    "Cwb",
    "Cwc",
    "Dfa",
    "Dfb",
    "Dfc",
    "Dfd",
    "Dsa",
    "Dsb",
    "Dsc",
    "Dsd",
    "Dwa",
    "Dwb",
    "Dwc",
    "Dwd",
    "ET",
    "EF"
  )

kcc_label <- c(
    "Af: Tropical (Rainforest)",
    "Am: Tropical (Monsoon)",
    "As: Tropical (Savanna, Dry S)",
    "Aw: Tropical (Savanna, Dry W)",
    "BSh: Dry (Semi-arid steppe Hot)",
    "BSk: Dry (Semi-arid steppe Cold)",
    "BWh: Dry (Arid desert Hot)",
    "BWk: Dry (Arid desert Cold)",
    "Cfa: Temperate (No dry season Hot S)",
    "Cfb: Temperate (No dry season Warm S)",
    "Cfc: Temperate (No dry season Cold S)",
    "Csa: Temperate (Dry summer Hot S)",
    "Csb: Temperate (Dry summer Warm S)",
    "Csc: Temperate (Dry summer Cold S)",
    "Cwa: Temperate (Dry winter Hot S)",
    "Cwb: Temperate (Dry winter Warm S)",
    "Cwc: Temperate (Dry winter Cold S)",
    "Dfa: Continental (No dry season Hot S)",
    "Dfb: Continental (No dry season Warm S)",
    "Dfc: Continental (No dry season Cold S)",
    "Dfd: Continental (No dry season Very cold S)",
    "Dsa: Continental (Dry winter Hot S)",
    "Dsb: Continental (Dry winter Warm S)",
    "Dsc: Continental (Dry winter Cold S)",
    "Dsd: Continental (Dry winter Very cold S)",
    "Dwa: Continental (Dry summer Hot S)",
    "Dwb: Continental (Dry summer Warm S)",
    "Dwc: Continental (Dry summer Cold S)",
    "Dwd: Continental (Dry summer Very cold S)",
    "ET: Polar (Tundra)",
    "EF: Polar Ice Cap"
  )

kcc_dict  <- data.frame(zone= kcc_zone, label=kcc_label)

```

### Palettes

```{r ktc palette}

 ktc_color <- c(
    "#040ff0",
    "#0474fb",
    "#ffe505",
    "#ff9005",
    "#0eff00",
    "#2db83d",
    "#b64dff",
    "#7c00ff",
    "#017783",
    "#72b8ce",
    "#b4dfe3"
  )

ktc_palette  <- data.frame(zone= ktc_zone, color=ktc_color)

```

```{r kcc palette}

 kcc_color <- c(
    "#0000fe",
    "#0277ff",
    "#7abaec",
    "#45a9f9",
    "#f5a300",
    "#ffdb63",
    "#fe0100",
    "#fe9695", 
    "#c7ff4f",
    "#66ff33",
    "#32c702",
    "#ffff00",
    "#c6c701",
    "#969600",
    "#96ff96",
    "#63c764",
    "#329633",
    "#03ffff",
    "#37c7ff",
    "#007e7d",
    "#00455e",
    "#ff00fe",
    "#c600c7",
    "#863295",
    "#966495",
    "#abb1ff",
    "#5a77db",
    "#4c51b5",
    "#320087",
    "#b2b2b2",
    "#686868"
  )

kcc_palette  <- data.frame(zone= kcc_zone, color=kcc_color)

```

### Map Projections

```{r}
rbn_prj <- "ESRI:54030"
```

### Read transformed climate period data

```{r read-transformed-data}

typ <- "crp"

pth <- paste(dir_transform, typ, "-nc-summary.csv", sep = "")
crp_nc_summary_df <- read_csv(pth, show_col_types = FALSE) 

pth <- paste(dir_transform, typ, "-monthly-data-t.parquet", sep = "")
crp_t_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-monthly-data-p.parquet", sep = "")
crp_p_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-t.parquet", sep = "")
crp_t_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-p.parquet", sep = "")
crp_p_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-climate-normals.parquet", sep = "")
crp_cn_df <- read_parquet(pth) 

typ <- "cpa"

pth <- paste(dir_transform, typ, "-nc-summary.csv", sep = "")
crp_nc_summary_df <- read_csv(pth, show_col_types = FALSE) 

pth <- paste(dir_transform, typ, "-monthly-data-t.parquet", sep = "")
cpa_t_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-monthly-data-p.parquet", sep = "")
cpa_p_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-t.parquet", sep = "")
cpa_t_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-p.parquet", sep = "")
cpa_p_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-climate-normals.parquet", sep = "")
cpa_cn_df <- read_parquet(pth) 

```

## Classification

### KTC classification function

```{r classify_ktc}
fn_classify_ktc <- function(df) {

# Step 1: Add seasonal precip stats (Summer/Winter) based on hemisphere
#         Summer: high sun 6 months (SH: Oct–Mar, NH: Apr–Sep)
#         Winter: low  sun 6 months (NH: Oct–Mar, SH: Apr–Sep)
  df <- df |>
    mutate(
      pST = case_when(lat >= 0 ~ pats, TRUE ~ potm),
      pWT = case_when(lat >= 0 ~ potm, TRUE ~ pats),
      pMnST = case_when(lat >= 0 ~ pmna, TRUE ~ pmno),
      pMxST = case_when(lat >= 0 ~ pmxa, TRUE ~ pmxo),
      pMnWT = case_when(lat >= 0 ~ pmno, TRUE ~ pmna),
      pMxWT = case_when(lat >= 0 ~ pmxo, TRUE ~ pmxa)
    )

# Step 2: Calculate Aridity threshold
  df <- df |>
    mutate(
      athr = case_when(
        ptot != 0 ~ (10 * (tavg - 10)) + (3 * (pST / ptot) * 100),
        TRUE ~ 10 * (tavg - 10)
      )
    )

# Step 3: Assign Primary Group
  df <- df |>
    mutate(
      z1 = case_when(
        tmax < 10 ~ "F",
        ptot < (athr * 2) ~ "B",
        tmin >= 18 ~ "A",
        tg10 >= 8 ~ "C",
        tg10 >= 4 ~ "D",
        tg10 >= 1 ~ "E",
        TRUE ~ "X"
      ),
      zn = ""
    )

# Step 4: Assign secondary group
  df <- df |>
    mutate(
      z2 = case_when(
        z1 == "A" & pl60 <= 2 ~ "r",
        z1 == "A" ~ "w",
        z1 == "B" & ptot < athr ~ "W",
        z1 == "B" ~ "S",
        z1 == "C" & pWT >= pST * 3 & pmin < 30 & ptot < 890 ~ "s",
        z1 == "C" ~ "f",
        z1 == "D" & tmin > 0 ~ "o",
        z1 == "D" ~ "c",
        z1 == "F" & tmax > 0 ~ "t",
        z1 == "F" ~ "i",
        TRUE ~ ""
      ),
      zn = paste(z1, z2, sep = "")
    )
  return(df)
}
```

### Classify climate periods using KTC

```{r ktc-crp-zones}

ktc_crp_cn_df <- fn_classify_ktc(crp_cn_df)
ktc_crp_cn_df <- ktc_crp_cn_df |> select(lon, lat, zn, area, lsm)
ktc_crp_cn_sf <- st_as_sf(ktc_crp_cn_df, coords = c("lon", "lat"), crs = 4326)

ktc_d_df <- fn_classify_ktc(cpa_cn_df)
ktc_d_df <- ktc_d_df |> select(lon, lat, zn, area, lsm)
ktc_d_sf <- st_as_sf(ktc_d_df, coords = c("lon", "lat"), crs = 4326)

# combine areas by crp and cpa

ktc_cd_sf <- ktc_crp_cn_sf
ktc_cd_sf <- ktc_cd_sf |> rename(czn = zn)
ktc_cd_sf$dzn <- ktc_d_sf$zn

ktc_grp_geom_sf <- ktc_cd_sf |>
  filter(lsm==1) |>
  summarise(
    geometry = st_combine(geometry),
    mkm = sum(area),
    .by = c(czn, dzn)
  ) |>
  mutate(cz1 = substr(czn, 1, 1)) |>
  mutate(dz1 = substr(dzn, 1, 1)) |>
  mutate(pct = round(mkm / sum(mkm) * 100, 3)) |>
  select(czn, cz1, dzn, dz1, mkm, pct, geometry) |>
  arrange(czn, dzn)
ktc_grp_geom_sf <- st_set_crs(ktc_grp_geom_sf, 4326)

```

### KCC classification function

 ```{r kcc-seasonal-stats}
fn_classify_kcc <- function(df) {

# Step 1: Add seasonal precip stats (Summer/Winter) based on hemisphere
#         Summer: high sun 6 months (SH: Oct–Mar, NH: Apr–Sep)
#         Winter: low  sun 6 months (NH: Oct–Mar, SH: Apr–Sep)
  df <- df |>
    mutate(
      pSK = case_when(lat >= 0 ~ pats, TRUE ~ potm),
      pWK = case_when(lat >= 0 ~ potm, TRUE ~ pats),
      pMnSK = case_when(lat >= 0 ~ pmna, TRUE ~ pmno),
      pMxSK = case_when(lat >= 0 ~ pmxa, TRUE ~ pmxo),
      pMnWK = case_when(lat >= 0 ~ pmno, TRUE ~ pmna),
      pMxWK = case_when(lat >= 0 ~ pmxo, TRUE ~ pmxa)
    )

# Step 2: Calculate Precipitation threshold
  df <- df |>
    mutate(
      pthr = case_when(
        pSK / ptot >= 0.7 ~ tavg * 20 + 280,
         pSK / ptot >= 0.3 ~ tavg * 20 + 140,
         TRUE ~ tavg * 20
      )
    )

# Step 3: Assign Primary Group
  df <- df |>
    mutate(
      z1 = case_when(
        tmax < 10 ~ "E",
        ptot < pthr ~ "B",
        tmin > 18 ~ "A",
        tmax > 10 & tmin >= -3 ~ "C",
        tmax > 10 & tmin <= -3 ~ "D",
        TRUE ~ ""
      ),
      z2 = ""
      # ,
      # k3 = "",
    )

# Step 4: Assign 2nd letter
  df <- df |>
    mutate(
      z2 = case_when(
        z1 == "A" & pmin >= 60 ~ "f",
        z1 == "A" & pmin < 60 & pmin >= (100 - ptot / 25) ~ "m",
        z1 == "A" & pmin < (100 - ptot / 25) & pWK > pSK ~ "w",
        z1 == "A" ~ "s",

        z1 == "B" & ptot <= (pthr * 0.5) ~ "W",
        z1 == "B" ~ "S",

        z1 == "C" & pMnSK < 40 & pMxWK >= pMnSK * 3 ~ "s",
        z1 == "C" & pMxSK >= pMnWK * 10 ~ "w",
        z1 == "C" ~ "f",

        z1 == "D" & pMnSK < 40 & pMxWK >= pMnSK * 3 ~ "s",
        z1 == "D" & pMxSK >= pMnWK * 10 ~ "w",
        z1 == "D" ~ "f",

        z1 == "E" & tmax > 0 ~ "T",
        z1 == "E" & tmax <= 0 ~ "F",

        TRUE ~ ""
      ),
    zn = paste(z1, z2, sep = "")    
    )

# Step 5: Assign 3rd letter
  df <- df |> 
    mutate(
      z3 = case_when(
        z1 == "B" & tavg >= 18 ~ "h",
        z1 == "B" ~ "k",

        z1 == "C" & tmax >= 22 ~ "a",
        z1 == "C" & tg10 >= 4 ~ "b",
        z1 == "C" ~ "c",

        z1 == "D" & tmax >= 22 ~ "a",
        z1 == "D" & tg10 >= 4 ~ "b",
        z1 == "D" & tmin < -38 ~ "d",
        z1 == "D" ~ "c",

        TRUE ~ ""
      ),
    zn = paste(z1, z2, z3,sep = "")  
    )
}

# Alternate threshold definition:
#   # Summer in Koppen is defined as warmer 6 month period of Oct-Mar or Apr-Sep
#   # Winter in Koppen is defined as cooler 6 month period of Oct-Mar or Apr-Sep
#   dt <- dt |>
#     mutate(
#       pSK = case_when(
#         tAprSep >= tOctMar ~ pats,
#         TRUE ~ potm
#       ),
#       pWK = case_when(
#         tAprSep < tOctMar ~ pats,
#         TRUE ~ potm
#       ),
#       pMnSK = case_when(
#         tAprSep >= tOctMar ~ pmin(p4, p5, p6, p7, p8, p9),
#         TRUE ~ pmin(p1, p2, p3, p10, p11, p12),
#       ),
#       pMxSK = case_when(
#         tAprSep >= tOctMar ~ pmax(p4, p5, p6, p7, p8, p9),
#         TRUE ~ pmax(p1, p2, p3, p10, p11, p12),
#       ),
#       pMnWK = case_when(
#         tAprSep >= tOctMar ~ pmin(p1, p2, p3, p10, p11, p12),
#         TRUE ~ pmin(p4, p5, p6, p7, p8, p9),
#       ),
#       pMxWK = case_when(
#         tAprSep >= tOctMar ~ pmax(p1, p2, p3, p10, p11, p12),
#         TRUE ~ pmax(p4, p5, p6, p7, p8, p9),
#       ),
#     )
#   return(dt)
# }

 ```

### Classify climate periods using KCC

```{r kcc-crp-zones}

kcc_crp_cn_df <- fn_classify_kcc(crp_cn_df)
kcc_crp_cn_df <- kcc_crp_cn_df |> select(lon, lat, zn, area, lsm)
kcc_crp_cn_sf <- st_as_sf(kcc_crp_cn_df, coords = c("lon", "lat"), crs = 4326)

kcc_cpa_cn_df <- fn_classify_kcc(cpa_cn_df)
kcc_cpa_cn_df <- kcc_cpa_cn_df |> select(lon, lat, zn, area, lsm)
kcc_cpa_cn_sf <- st_as_sf(kcc_cpa_cn_df, coords = c("lon", "lat"), crs = 4326)

# combine areas by crp and cpa

kcc_cd_sf <- kcc_crp_cn_sf
kcc_cd_sf <- kcc_cd_sf |> rename(czn = zn)
kcc_cd_sf$dzn <- kcc_cpa_cn_sf$zn

kcc_grp_geom_sf <- kcc_cd_sf |>
  filter(lsm==1) |>
  summarise(
    geometry = st_combine(geometry),
    mkm = sum(area),
    .by = c(czn, dzn)
  ) |>
  mutate(cz1 = substr(czn, 1, 1)) |>
  mutate(dz1 = substr(dzn, 1, 1)) |>
  mutate(pct = round(mkm / sum(mkm) * 100, 3)) |>
  select(czn, cz1, dzn, dz1, mkm, pct, geometry) |>
  arrange(czn, dzn)
kcc_grp_geom_sf <- st_set_crs(kcc_grp_geom_sf, 4326)


```

## Summary

### KTC summary

```{r build-ktc-summary}

# Build CRP and CPA aggregates from grouped land geometries
ktc_crp_df <- ktc_grp_geom_sf |>
  st_drop_geometry() |>
  select(czn, cz1, mkm, pct) |>
  summarize(mkm = sum(mkm), pct = sum(pct), .by = c(czn, cz1)) |>
  mutate(period = "crp") |>
  rename(zone = czn, z1 = cz1) |>
  arrange(zone)

ktc_cpa_df <- ktc_grp_geom_sf |>
  st_drop_geometry() |>
  select(dzn, dz1, mkm, pct) |>
  summarize(mkm = sum(mkm), pct = sum(pct), .by = c(dzn, dz1)) |>
  mutate(period = "cpa") |>
  rename(zone = dzn, z1 = dz1) |>
  arrange(zone)

# Side-by-side comparison + deltas
ktc_diff_df <- ktc_crp_df |>
  select(zone, mkm, pct) |>
  rename(cmkm = mkm, cpct = pct)

ktc_diff_df$dmkm <- ktc_cpa_df$mkm
ktc_diff_df$dpct <- ktc_cpa_df$pct

ktc_diff_df <- ktc_diff_df |>
  mutate(
    xmkm = dmkm - cmkm,
    xpct = round(dpct - cpct, 2)
  ) |>
  select(zone, cmkm, dmkm, xmkm, cpct, dpct, xpct)

ktc_diff_df <- ktc_diff_df |>
  left_join(ktc_dict, by = "zone") |>
  select(label, cmkm, dmkm, xmkm, cpct, dpct, xpct)

ktc_diff_gt <- gt(ktc_diff_df)

```

```{r display-ktc-summary}

ktc_tbl1 <- ktc_diff_gt |>
  tab_header(
    title = "Summary of Köppen-Trewartha Climate Zone Changes",
    #subtitle = paste(crp_lbl, "vs", cpa_lbl)
  ) |>
  tab_spanner(
    label = "Area (Mkm²)",
    columns = c(cmkm, dmkm, xmkm)
  ) |>
  tab_spanner(
    label = "Earth Land Area %",
    columns = c(cpct, dpct, xpct)
  ) |>
  cols_label(
    cmkm = "CRP",
    dmkm = "CPA",
    xmkm = "Chg",
    cpct = "CRP",
    dpct = "CPA",
    xpct = "Chg"
  ) |>
  fmt_number(columns = c(cmkm, dmkm, xmkm), decimals = 1) |>
  fmt_number(columns = c(cpct, dpct, xpct), decimals = 2) |>
  grand_summary_rows(
    columns = c(cmkm, dmkm, xmkm, cpct, dpct, xpct),
    fns = list("Total" = ~ sum(.)),
    fmt = list(~ fmt_number(.x, decimals = 2))
  ) |>
  tab_footnote(
    footnote = paste("CRP: Climate Reference Period ", crp_beg, "-", crp_end, sep = ""),
    locations = cells_column_labels(columns = c(cmkm, cpct))
  ) |>
  tab_footnote(
    footnote = paste("CPA: Decadal Climate Normals ", cpa_beg, "-", cpa_end, sep = ""),
    locations = cells_column_labels(columns = c(dmkm, dpct))
  )

ktc_tbl1 
```

### KCC summary

```{r build-kcc-summary}

# Build CRP and CPA aggregates from grouped land geometries
kcc_crp_df <- kcc_grp_geom_sf |>
  st_drop_geometry() |>
  select(czn, cz1, mkm, pct) |>
  summarize(mkm = sum(mkm), pct = sum(pct), .by = c(czn, cz1)) |>
  mutate(period = "crp") |>
  rename(zone = czn, z1 = cz1) |>
  arrange(zone)

kcc_cpa_df <- kcc_grp_geom_sf |>
  st_drop_geometry() |>
  select(dzn, dz1, mkm, pct) |>
  summarize(mkm = sum(mkm), pct = sum(pct), .by = c(dzn, dz1)) |>
  mutate(period = "cpa") |>
  rename(zone = dzn, z1 = dz1) |>
  arrange(zone)

# Side-by-side comparison + deltas
kcc_diff_df <- kcc_crp_df |>
  select(zone, mkm, pct) |>
  rename(cmkm = mkm, cpct = pct)

kcc_diff_df <- kcc_diff_df |>
  inner_join(kcc_cpa_df, by = "zone") |>
  rename(dmkm = mkm, dpct = pct)

# kcc_diff_df$dmkm <- kcc_cpa_df$mkm
# kcc_diff_df$dpct <- kcc_cpa_df$pct

kcc_diff_df <- kcc_diff_df |>
  mutate(
    xmkm = dmkm - cmkm,
    xpct = round(dpct - cpct, 2)
  ) |>
  select(zone, cmkm, dmkm, xmkm, cpct, dpct, xpct)

kcc_diff_df <- kcc_diff_df |>
  inner_join(kcc_dict, by = "zone") |>
  select(label, cmkm, dmkm, xmkm, cpct, dpct, xpct)

kcc_diff_gt <- gt(kcc_diff_df)

```

```{r display-kcc-summary}

kcc_tbl1 <- kcc_diff_gt |>
  tab_header(
    title = "Summary of Köppen Climate Zone Changes",
    #subtitle = paste(crp_lbl, "vs", cpa_lbl)
  ) |>
  tab_spanner(
    label = "Area (Mkm²)",
    columns = c(cmkm, dmkm, xmkm)
  ) |>
  tab_spanner(
    label = "Earth Land Area %",
    columns = c(cpct, dpct, xpct)
  ) |>
  cols_label(
    cmkm = "CRP",
    dmkm = "CPA",
    xmkm = "Chg",
    cpct = "CRP",
    dpct = "CPA",
    xpct = "Chg"
  ) |>
  fmt_number(columns = c(cmkm, dmkm, xmkm), decimals = 1) |>
  fmt_number(columns = c(cpct, dpct, xpct), decimals = 2) |>
  grand_summary_rows(
    columns = c(cmkm, dmkm, xmkm, cpct, dpct, xpct),
    fns = list("Total" = ~ sum(.)),
    fmt = list(~ fmt_number(.x, decimals = 2))
  ) |>
  tab_footnote(
    footnote = paste("CRP: Climate Reference Period ", crp_beg, "-", crp_end, sep = ""),
    locations = cells_column_labels(columns = c(cmkm, cpct))
  ) |>
  tab_footnote(
    footnote = paste("CPA: Decadal Climate Normals ", cpa_beg, "-", cpa_end, sep = ""),
    locations = cells_column_labels(columns = c(dmkm, dpct))
  )

kcc_tbl1 

```


## Visualization


```{r read-coastline}
dir <- dir_transform
fil <- "global-coastline.gpkg"
pth <- paste(dir, fil, sep = "")
coastline_sf <- st_read(pth, quiet=TRUE)
```

### Map 1

```{r map-1}

plot_data <- ktc_grp_geom_sf |>
  select(czn) |>
  rename(zone = czn)
p1 <- ggplot(plot_data) +
  geom_sf(aes(color = zone), size = 0.1) +
  scale_color_manual(
    values = setNames(ktc_palette$color, ktc_palette$zone),
    labels = setNames(ktc_dict$label, ktc_dict$zone)
  ) +
  geom_sf(
    data = coastline_sf,
    color = "darkgrey",
    linewidth = 0.1
  ) +
  coord_sf(crs = rbn_prj) +
  labs(
    title = "Köppen-Trewartha Climate Classification",
    subtitle = crp_lbl,
    color = "Zones"
  ) +
  guides(
    color = guide_legend(
      override.aes = list(
        size = 3 # legend point size only
      )
    )
  )
p1

```

### Map 2

```{r map-2}

plot_data <- kcc_grp_geom_sf |>
  select(czn) |>
  rename(zone = czn)

p2 <- ggplot(plot_data) +
  geom_sf(aes(color = zone), size = 0.1) +
  scale_color_manual(
    values = setNames(kcc_palette$color, kcc_palette$zone),
    labels = setNames(kcc_dict$label, kcc_dict$zone)
  ) +
  geom_sf(
    data = coastline_sf,
    color = "darkgrey",
    linewidth = 0.1
  ) +
  coord_sf(crs = rbn_prj) +
  labs(
    title = "Köppen Climate Classification",
    subtitle = crp_lbl,
    color = "Zones"
  ) +
  guides(
    color = guide_legend(
      override.aes = list(
        size = 3 # legend point size only
      )
    )
  )
p2

```
