---
title: "Derive Classification Metrics"
---

### Packages

```{r}
#| label: pkg
suppressPackageStartupMessages({
  library(tidyverse)
  library(arrow)
  library(gt)
})
```

### Climatological Reference Period 

```{r}
#| label: crp
crp_beg <- 1961
crp_end <- 1990
```

### Recent Climate Period

```{r}
# label: rcp
rcp_beg <- 2011
rcp_end <- 2020
```

### Paths

```{r}
#| label: pth
dir_rd <- "_data/03-data-reshaping/"
dir_wr <- "_data/04-annual-summaries/"
```

```{r}
  fil <- "crp_t_wide.parquet"
  pth <- paste0(dir_rd, fil)
  df <- read_parquet(pth) 
```
### Functions

```{r}
fn_annual_stats <- function(crp, cv, dir_rd, dir_wr) {

  fil <- paste0(crp, "_", cv, "_wide.parquet")
  pth <- paste0(dir_rd, fil)
  df <- read_parquet(pth) 

  mcols <- paste0("m", 1:12)

  df <- df |>
    mutate(
      yavg = ((m1 + m2 + m3 + m4 + m5 + m6 + m7 + m8 + m9 + m10 + m11 + m12) / 12),
      ymax = pmax(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12),
      ymin = pmin(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12),
      qtr1 = (m1 + m2 + m3) / 3,
      qtr2 = (m4 + m5 + m6) / 3,
      qtr3 = (m7 + m8 + m9) / 3,
      qtr4 = (m10 + m11 + m12) / 3)

  df <- df |>
      mutate(
        wavg = case_when(
          lat >= 0 ~ (m1 + m2 + m3 + m10 + m11 + m12) / 6,
          lat < 0 ~ (m4 + m5 + m6 + m7 + m8 + m9) / 6
        ),
        wmax = case_when(
          lat >= 0 ~ pmax(m10, m11, m12, m1, m2, m3),
          lat < 0 ~ pmax(m4, m5, m6, m7, m8, m9) / 6
        ),
        wmin = case_when(
          lat >= 0 ~ pmin(m10, m11, m12, m1, m2, m3),
          lat < 0 ~ pmin(m4, m5, m6, m7, m8, m9) / 6
        ),
        savg = case_when(
          lat >= 0 ~ (m4 + m5 + m6 + m7 + m8 + m9) / 6,
          lat < 0 ~  (m1 + m2 + m3 + m10 + m11 + m12)/ 6
        ),
        smax = case_when(
          lat >= 0 ~ pmax(m4, m5, m6, m7, m8, m9) /6,
          lat < 0 ~ pmax(m10, m11, m12, m1, m2, m3)/ 6
        ),
        smin = case_when(
          lat >= 0 ~ pmin(m4, m5, m6, m7, m8, m9) / 6,
          lat < 0 ~ pmin(m10, m11, m12, m1, m2, m3)
        )
      )

  if (cv == "t") {
    df <- df |>
      mutate(
        tg10 = rowSums(across(all_of(mcols), ~ .x >= 10)))
    } else {
    df <- df |>
      mutate(
        pl60 = rowSums(across(all_of(mcols), ~ .x < 60)))
    }

  df <- df |>
    select(-m1, -m2, -m3, -m4, -m5, -m6, -m7, -m8, -m9, -m10, -m11, -m12)

  fil <- paste0(crp, "_", cv, "_annual.parquet")
  pth = paste0(dir_wr, fil)
  write_parquet(df, pth)
}

```

### Calculate annual and seasonal stats

```{r}
#| label: pvt
fn_annual_stats("crp", "t", dir_rd, dir_wr)
fn_annual_stats("crp", "p", dir_rd, dir_wr)
fn_annual_stats("rcp", "t", dir_rd, dir_wr)
fn_annual_stats("rcp", "p", dir_rd, dir_wr)
```

### Summarize Results


```{r}
#| label: fn-summarize-df
fn_summarize_df <- function(dir, cp, cv) {
  fil <- paste0(cp, "_", cv, "_annual.parquet")
  pth <- paste0(dir,fil)
  df <- read_parquet(pth)
  df_means <- df |> 
    select(-c(1:2)) |> 
    # this format is now recommended for dplyr
    summarise(across(everything(), \(x) mean(x, na.rm = TRUE))) |> 
    pivot_longer(everything(),
               names_to = "stat_id",
               values_to = "stat_value")

  return(df_means)
    
}
```


```{r}
#| label: main_summary

df1 <- fn_summarize_df(dir_wr, "crp", "t")
df2 <- fn_summarize_df(dir_wr, "crp", "p")
df3 <- fn_summarize_df(dir_wr, "rcp", "t")
df4 <- fn_summarize_df(dir_wr, "rcp", "p")


```

```{r}
#| label: join-stats-dfs
df_joined <- df1 |> 
  full_join(df2, by = "stat_id") |> 
  full_join(df3, by = "stat_id") |> 
  full_join(df4, by = "stat_id") |> 
  rename(
    crp_t = stat_value.x,
    crp_p = stat_value.y,
    rcp_t = stat_value.x.x,
    rcp_p = stat_value.y.y
  ) |> 
  mutate(
    stat_id = recode(stat_id,
      "yavg" = "Annual Avg",
      "ymax" = "Annual Max",
      "ymin" = "Annual Min",
      "qtr1" = "Q1 Avg",
      "qtr2" = "Q2 Avg",
      "qtr3" = "Q3 Avg",
      "qtr4" = "Q4 Avg",
      "wavg" = "Winter Avg",
      "wmax" = "Winter Max",
      "wmin" = "Winter Min",
      "savg" = "Summer Avg",
      "smax" = "Summer Max",
      "smin" = "Summer Min",
      "tg10" = "Months > 10C",
      "pl60" = "Months < 60mm"
    )
  )
```
### Build results df

```{r}
library(dplyr)
library(gt)

gt_tbl <- 
  df_joined |>
    gt(rowname_col = "stat_id") |>
    tab_header(
      title = "Climate Statistics by Station"
    ) |>
    tab_spanner(
      label = "Climatological Reference Period 1961-1990",
      columns = c(crp_t, crp_p)
    ) |>
    tab_spanner(
      label = "Recent Climate Period 2011-2020",
      columns = c(rcp_t, rcp_p)
    ) |>
    cols_label(
      crp_t = "CRP Temperature (°C)",
      crp_p = "CRP Precipitation (mm)",
      rcp_t = "RCP Temperature (°C)",
      rcp_p = "RCP Precipitation (mm)"
    ) |>
    fmt_number(
      columns = c(crp_t, crp_p, rcp_t, rcp_p),
      decimals = 2
   )

gt_tbl
```