---
title: "Classify Koppen"
---

## Setup

### Packages

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ecmwfr)
  library(tidync)
  library(data.table)
  library(sf)
  library(arrow)
  library(units)

  library(gt)
  #library(gtExtras)
  #library(htmltools)

  library(RColorBrewer)
  library(viridis)
  library(scales) # for cut_number
  library(rnaturalearth)
})
```

### Climate Periods

```{r climate-periods}

# Climatological Standard Reference Period Normals
crp_beg <- 1961
crp_end <- 1990
crp_lbl <- paste("CRP ", crp_beg, "-", crp_end, sep = "")

# Climatological Period Average
rcp_beg <- 2011
rcp_end <- 2020
rcp_lbl <- paste("rcp ", rcp_beg, "-", rcp_end, sep = "")
```

### Paths

```{r paths}
dir_transform <- "_data/2-transform/"
dir_classify <- "_data/classify/"
```

```{r figures-output}
# Centralize figures created by chunks in this doc
knitr::opts_chunk$set(fig.path = "_figures/classify-")
```

### Dictionaries


```{r kcc-dictionary}

kcc_zone <- c(
    "Af",
    "Am",
    "As",
    "Aw",
    "BSh",
    "BSk",
    "BWh",
    "BWk",
    "Cfa",
    "Cfb",
    "Cfc",
    "Csa",
    "Csb",
    "Csc",
    "Cwa",
    "Cwb",
    "Cwc",
    "Dfa",
    "Dfb",
    "Dfc",
    "Dfd",
    "Dsa",
    "Dsb",
    "Dsc",
    "Dsd",
    "Dwa",
    "Dwb",
    "Dwc",
    "Dwd",
    "ET",
    "EF"
  )

kcc_label <- c(
    "Af: Tropical (Rainforest)",
    "Am: Tropical (Monsoon)",
    "As: Tropical (Savanna, Dry S)",
    "Aw: Tropical (Savanna, Dry W)",
    "BSh: Dry (Semi-arid steppe Hot)",
    "BSk: Dry (Semi-arid steppe Cold)",
    "BWh: Dry (Arid desert Hot)",
    "BWk: Dry (Arid desert Cold)",
    "Cfa: Temperate (No dry season Hot S)",
    "Cfb: Temperate (No dry season Warm S)",
    "Cfc: Temperate (No dry season Cold S)",
    "Csa: Temperate (Dry summer Hot S)",
    "Csb: Temperate (Dry summer Warm S)",
    "Csc: Temperate (Dry summer Cold S)",
    "Cwa: Temperate (Dry winter Hot S)",
    "Cwb: Temperate (Dry winter Warm S)",
    "Cwc: Temperate (Dry winter Cold S)",
    "Dfa: Continental (No dry season Hot S)",
    "Dfb: Continental (No dry season Warm S)",
    "Dfc: Continental (No dry season Cold S)",
    "Dfd: Continental (No dry season Very cold S)",
    "Dsa: Continental (Dry winter Hot S)",
    "Dsb: Continental (Dry winter Warm S)",
    "Dsc: Continental (Dry winter Cold S)",
    "Dsd: Continental (Dry winter Very cold S)",
    "Dwa: Continental (Dry summer Hot S)",
    "Dwb: Continental (Dry summer Warm S)",
    "Dwc: Continental (Dry summer Cold S)",
    "Dwd: Continental (Dry summer Very cold S)",
    "ET: Polar (Tundra)",
    "EF: Polar Ice Cap"
  )

kcc_dict  <- data.frame(zone= kcc_zone, label=kcc_label)

```

### Palettes

```{r kcc palette}

 kcc_color <- c(
    "#0000fe",
    "#0277ff",
    "#7abaec",
    "#45a9f9",
    "#f5a300",
    "#ffdb63",
    "#fe0100",
    "#fe9695", 
    "#c7ff4f",
    "#66ff33",
    "#32c702",
    "#ffff00",
    "#c6c701",
    "#969600",
    "#96ff96",
    "#63c764",
    "#329633",
    "#03ffff",
    "#37c7ff",
    "#007e7d",
    "#00455e",
    "#ff00fe",
    "#c600c7",
    "#863295",
    "#966495",
    "#abb1ff",
    "#5a77db",
    "#4c51b5",
    "#320087",
    "#b2b2b2",
    "#686868"
  )

kcc_palette  <- data.frame(zone= kcc_zone, color=kcc_color)

```

### Map Projections

```{r}
rbn_prj <- "ESRI:54030"
```

### Read transformed climate period data

```{r read-transformed-data}

typ <- "crp"

pth <- paste(dir_transform, typ, "-nc-summary.csv", sep = "")
crp_nc_summary_df <- read_csv(pth, show_col_types = FALSE) 

pth <- paste(dir_transform, typ, "-monthly-data-t.parquet", sep = "")
crp_t_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-monthly-data-p.parquet", sep = "")
crp_p_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-t.parquet", sep = "")
crp_t_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-p.parquet", sep = "")
crp_p_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-period-average.parquet", sep = "")
crp_cn_df <- read_parquet(pth) 

typ <- "rcp"

pth <- paste(dir_transform, typ, "-nc-summary.csv", sep = "")
crp_nc_summary_df <- read_csv(pth, show_col_types = FALSE) 

pth <- paste(dir_transform, typ, "-monthly-data-t.parquet", sep = "")
rcp_t_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-monthly-data-p.parquet", sep = "")
rcp_p_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-t.parquet", sep = "")
rcp_t_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-p.parquet", sep = "")
rcp_p_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-period-average.parquet", sep = "")
rcp_cn_df <- read_parquet(pth) 

```

## Classification

### KCC classification function

```{r fn-classify-kcc}
fn_classify_kcc <- function(df) {

# Step 1: Add seasonal precip stats (Summer/Winter) based on hemisphere
#         Summer: high sun 6 months (SH: Oct–Mar, NH: Apr–Sep)
#         Winter: low  sun 6 months (NH: Oct–Mar, SH: Apr–Sep)
  df <- df |>
    mutate(
      pSK = case_when(lat >= 0 ~ pats, TRUE ~ potm),
      pWK = case_when(lat >= 0 ~ potm, TRUE ~ pats),
      pMnSK = case_when(lat >= 0 ~ pmna, TRUE ~ pmno),
      pMxSK = case_when(lat >= 0 ~ pmxa, TRUE ~ pmxo),
      pMnWK = case_when(lat >= 0 ~ pmno, TRUE ~ pmna),
      pMxWK = case_when(lat >= 0 ~ pmxo, TRUE ~ pmxa)
    )

# Step 2: Calculate Precipitation threshold
  df <- df |>
    mutate(
      pthr = case_when(
        pSK / ptot >= 0.7 ~ tavg * 20 + 280,
         pSK / ptot >= 0.3 ~ tavg * 20 + 140,
         TRUE ~ tavg * 20
      )
    )

# Step 3: Assign Primary Group
  df <- df |>
    mutate(
      z1 = case_when(
        tmax < 10 ~ "E",
        ptot < pthr ~ "B",
        tmin > 18 ~ "A",
        tmax > 10 & tmin >= -3 ~ "C",
        tmax > 10 & tmin <= -3 ~ "D",
        TRUE ~ ""
      ),
      z2 = ""
      # ,
      # k3 = "",
    )

# Step 4: Assign 2nd letter
  df <- df |>
    mutate(
      z2 = case_when(
        z1 == "A" & pmin >= 60 ~ "f",
        z1 == "A" & pmin < 60 & pmin >= (100 - ptot / 25) ~ "m",
        z1 == "A" & pmin < (100 - ptot / 25) & pWK > pSK ~ "w",
        z1 == "A" ~ "s",

        z1 == "B" & ptot <= (pthr * 0.5) ~ "W",
        z1 == "B" ~ "S",

        z1 == "C" & pMnSK < 40 & pMxWK >= pMnSK * 3 ~ "s",
        z1 == "C" & pMxSK >= pMnWK * 10 ~ "w",
        z1 == "C" ~ "f",

        z1 == "D" & pMnSK < 40 & pMxWK >= pMnSK * 3 ~ "s",
        z1 == "D" & pMxSK >= pMnWK * 10 ~ "w",
        z1 == "D" ~ "f",

        z1 == "E" & tmax > 0 ~ "T",
        z1 == "E" & tmax <= 0 ~ "F",

        TRUE ~ ""
      ),
    zn = paste(z1, z2, sep = "")    
    )

# Step 5: Assign 3rd letter
  df <- df |> 
    mutate(
      z3 = case_when(
        z1 == "B" & tavg >= 18 ~ "h",
        z1 == "B" ~ "k",

        z1 == "C" & tmax >= 22 ~ "a",
        z1 == "C" & tg10 >= 4 ~ "b",
        z1 == "C" ~ "c",

        z1 == "D" & tmax >= 22 ~ "a",
        z1 == "D" & tg10 >= 4 ~ "b",
        z1 == "D" & tmin < -38 ~ "d",
        z1 == "D" ~ "c",

        TRUE ~ ""
      ),
    zn = paste(z1, z2, z3,sep = "")  
    )
}
```

### Classify climate periods using KCC

```{r classify-kcc}

kcc_crp_cn_df <- fn_classify_kcc(crp_cn_df)
kcc_crp_cn_df <- kcc_crp_cn_df |> select(lon, lat, zn, area, lsm)
kcc_crp_cn_sf <- st_as_sf(kcc_crp_cn_df, coords = c("lon", "lat"), crs = 4326)

kcc_rcp_cn_df <- fn_classify_kcc(rcp_cn_df)
kcc_rcp_cn_df <- kcc_rcp_cn_df |> select(lon, lat, zn, area, lsm)
kcc_rcp_cn_sf <- st_as_sf(kcc_rcp_cn_df, coords = c("lon", "lat"), crs = 4326)

# combine areas by crp and rcp

kcc_cr_sf <- kcc_crp_cn_sf
kcc_cr_sf <- kcc_cr_sf |> rename(czn = zn)
kcc_cr_sf$rzn <- kcc_rcp_cn_sf$zn

kcc_grp_geom_sf <- kcc_cr_sf |>
  filter(lsm==1) |>
  summarise(
    geometry = st_combine(geometry),
    mkm = sum(area),
    .by = c(czn, rzn)
  ) |>
  mutate(cz1 = substr(czn, 1, 1)) |>
  mutate(rz1 = substr(rzn, 1, 1)) |>
  mutate(pct = round(mkm / sum(mkm) * 100, 3)) |>
  select(czn, cz1, rzn, rz1, mkm, pct, geometry) |>
  arrange(czn, rzn)
kcc_grp_geom_sf <- st_set_crs(kcc_grp_geom_sf, 4326)


```

## Summary

### KCC summary


```{r}

kcc_crp_df <- kcc_grp_geom_sf |>
  st_drop_geometry() |>
  select(czn, cz1, mkm, pct) |>
  summarize(mkm = sum(mkm), pct = sum(pct), .by = c(czn, cz1)) |>
  mutate(period = "crp") |>
  rename(zone = czn, z1 = cz1) |>
  arrange(zone)

kcc_rcp_df <- kcc_grp_geom_sf |>
  st_drop_geometry() |>
  select(rzn, rz1, mkm, pct) |>
  summarize(mkm = sum(mkm), pct = sum(pct), .by = c(rzn, rz1)) |>
  mutate(period = "rcp") |>
  rename(zone = rzn, z1 = rz1) |>
  arrange(zone)

kcc_diff_df <- kcc_crp_df |>
  select(zone, mkm, pct) |>
  rename(cmkm = mkm, cpct = pct)

kcc_diff_df <- kcc_diff_df |>
  inner_join(kcc_rcp_df, by = "zone") |>
  rename(rmkm = mkm, rpct = pct)

kcc_diff_df <- kcc_diff_df |>
  mutate(
    xmkm = rmkm - cmkm,
    xpct = round(rpct - cpct, 2)
  ) |>
  select(zone, cmkm, rmkm, xmkm, cpct, rpct, xpct)

kcc_diff_gt <- kcc_diff_df |> gt(rowname_col = "zone")
```


```{r display-kcc-summary}

kcc_tbl1 <- kcc_diff_gt |>
  tab_header(
    title = "Summary of Köppen Climate Zone Changes",
  ) |>
  tab_spanner(
    label = "Area (Mkm²)",
    columns = c(cmkm, rmkm, xmkm)
  ) |>
  tab_spanner(
    label = "Earth Land Area %",
    columns = c(cpct, rpct, xpct)
  ) |>
  cols_label(
    cmkm = "CRP",
    rmkm = "rcp",
    xmkm = "Chg",
    cpct = "CRP",
    rpct = "rcp",
    xpct = "Chg"
  ) |>
  fmt_number(columns = c(cmkm, rmkm, xmkm), decimals = 1) |>
  fmt_number(columns = c(cpct, rpct, xpct), decimals = 2) |>
  grand_summary_rows(
    columns = c(cmkm, rmkm, xmkm, cpct, rpct, xpct),
    fns = list("Total" = ~ sum(.)),
    fmt = list(~ fmt_number(.x, decimals = 2))
  ) |>
  tab_footnote(
    footnote = paste("CRP: Climate Reference Period ", crp_beg, "-", crp_end, sep = ""),
    locations = cells_column_labels(columns = c(cmkm, cpct))
  ) |>
  tab_footnote(
    footnote = paste("rcp: Climate Period Average ", rcp_beg, "-", rcp_end, sep = ""),
    locations = cells_column_labels(columns = c(rmkm, rpct))
  )

kcc_tbl1 
```


## Visualization

```{r read-coastline}
dir <- dir_transform
fil <- "ne-coastline.gpkg"
pth <- paste(dir, fil, sep = "")
coastline_sf <- st_read(pth, quiet=TRUE)
```

### Map 1

```{r}
#| label: map-kcc-crp
plot_data <- kcc_grp_geom_sf |>
  select(czn) |>
  rename(zone = czn)

p1 <- ggplot(plot_data) +
  geom_sf(aes(color = zone), size = 0.1) +
  scale_color_manual(
    values = setNames(kcc_palette$color, kcc_palette$zone),
    labels = setNames(kcc_dict$zone, kcc_dict$zone)
  ) +
  geom_sf(
    data = coastline_sf,
    color = "darkgrey",
    linewidth = 0.1
  ) +
  coord_sf(crs = rbn_prj) +
  labs(
    title = "Köppen Climate Classification",
    subtitle = crp_lbl,
    color = "Zones"
  ) +
  guides(
    color = guide_legend(
      override.aes = list(
        size = 3 # legend point size only
      )
    )
  )
```


 ```{r}
#| label: fig:kcc-crp-classification
#| fig-cap: "Koppen classification (1961–1990)."
p1
 ```
