---
title: "Change Analysis"
---

## Periods
```{r}
#| label: periods
# Climatological Reference Period
crp = "crp"
crp_beg <- 1961
crp_end <- 1990
crp_lbl <- paste("CRP ", crp_beg, "-", crp_end, sep = "")
# Recent Climate Period
dcp = "dcp"
dcp_beg <- 2015
dcp_end <- 2024
dcp_lbl <- paste("DCP ", dcp_beg, "-", dcp_end, sep = "")
```

## Packages
```{r}
#| label: packages
suppressPackageStartupMessages({
  library(tidyverse)
  library(sf)
  library(arrow)
  library(units)
  library(gt)
  library(patchwork)
})
```

## Directories
```{r}
#| label: directories
dir_rf <- "data/00_reference/"
climate_classification_dir <- "data/04_climate_classification/"
```


## Palette
```{r}
#| label: palette
pth <- paste0(dir_rf,"ktc_group_palette.csv")
palette_df<- read_csv(pth, show_col_types = FALSE)
grp_levels <- palette_df$grp
grp_palette <- setNames(
  palette_df$hex,
  palette_df$grp
)
```

## Projections
```{r}
#| label: projections
rbn_prj <- "ESRI:54030"
```

## Coastline
```{r}
#| label: coastline
dir <- dir_rf
fil <- "global-coastline.gpkg"
pth <- paste(dir, fil, sep = "")
coastline_sf <- st_read(pth, quiet=TRUE)
```

## Import
```{r}
#| label: import
pth <- paste(climate_classification_dir, "ktc_grp_classification.gpkg", sep = "")
import_sf <- st_read(pth, quiet=TRUE)

import_sf <- import_sf |>  
  mutate(cgrp = factor(cgrp, levels = grp_levels))
import_sf <- import_sf |>  
  mutate(rgrp = factor(rgrp, levels = grp_levels))
import_df <- import_sf |> 
  st_drop_geometry() 

# remove rows where rgrp and cgrp are the same
shifts_sf <- import_sf |> filter(cgrp != rgrp)
shifts_df <- import_df |> filter(cgrp != rgrp)


```

## Functions

```{r}
#| label: fn_build_summary_table

fn_build_summary_table <- function(df) {
  tbl <- df |>
    gt(rowname_col = "cg" ) |>
    tab_stubhead(label = "Group")|>
    tab_header(
      title = "Köppen-Trewartha Climate Classification",
      subtitle = "Group Changes Summary",
    ) |>
    tab_spanner(
      label = "Area (Mkm²)",
      columns = c(mkm_c, mkm_g, mkm_l, mkm_r, mkm_d)
    ) |>
    tab_spanner(
      label = "Group % of Total",
      columns = c(pct_c, pct_g, pct_l, pct_r, pct_d)
    ) |>
    cols_label(
      mkm_c = "CRP",
      mkm_g = "Gain",
      mkm_l = "Loss",
      mkm_r = "DCP",
      mkm_d = "Net Chg",

      pct_c = "CRP",
      pct_g = "Gain",
      pct_l = "Loss",
      pct_r = "DCP",
      pct_d = "Net Chg"
    ) |>
    fmt_number(
      columns = c(mkm_c, mkm_g, mkm_l, mkm_r, mkm_d),
      decimals = 1) |>
    fmt_percent(
      columns = c(pct_c, pct_g, pct_l, pct_r, pct_d),
      decimals = 1 
    ) |>
    grand_summary_rows(
      columns = c(mkm_c, mkm_g, mkm_l, mkm_r, mkm_d),
      fns = list("Total" = ~ sum(.)),
      fmt = list(~ fmt_number(.x, decimals = 1)) 
    ) |>
    grand_summary_rows(
      columns = c(pct_c, pct_g, pct_l, pct_r, pct_d),
      fns = list("Total" = ~ sum(.)),
      fmt = list(~ fmt_percent(.x, decimals = 1)) 
    ) |>
    tab_footnote(
      footnote = paste("Climatological Reference Period ", crp_beg, "-", crp_end, sep = ""),
      locations = cells_column_labels(columns = c(mkm_c, pct_c))
    ) |>
    tab_footnote(
      footnote = paste("Recent Climate Period ", dcp_beg, "-", dcp_end, sep = ""),
      locations = cells_column_labels(columns = c(mkm_r, pct_r))
    ) |>
    tab_style(
      style = cell_fill(color = "#e6f0fa"),
      locations = cells_body(columns = pct_g, rows = pct_g > .01)
    ) |>
    tab_style(
      style = cell_fill(color = "#c5d6e9"),
      locations = cells_body(columns = pct_g, rows = pct_g > .02)
    ) |>
    tab_style(
      style = cell_fill(color = "#fffad5"),
      locations = cells_body(columns = pct_l, rows = pct_l < -.01)
    ) |>
    tab_style(
      style = cell_fill(color = "#fff7bc"),
      locations = cells_body(columns = pct_l, rows = pct_l < -.02)
    ) |>
    tab_style(
      style = cell_fill(color = "#c5d6e9"),
      locations = cells_body(columns = pct_d, rows = pct_d > .02)
    ) |>
    tab_style(
      style = cell_fill(color = "#fff7bc"),
      locations = cells_body(columns = pct_d, rows = pct_d < -.01)
    )

  return(tbl)
}
```

```{r}
#| label: fn_build_detail_table

fn_build_detail_table <- function(df, subtitle) {

  tbl <- df |>
    gt(rowname_col = "cgrp" ) |>
    tab_stubhead(label = "From Group")|>
    tab_header(
      title = "Climate Classification Changes Detail",
      subtitle = subtitle
    ) |>
    cols_label(
      rgrp = "To Group",
      mkm = "Area (Mkm²)",
      pct = "Land Area %",
    ) |>
    fmt_number(
      columns = mkm,
      decimals = 1
    ) |>
    fmt_percent(
      columns = pct,
      decimals = 2 
    ) |>
    # cols_width(
    #     col_a ~ px(150), # Set col_a to 150 pixels
    #     col_b ~ pct(10), # Set col_b to 10% of table width
    #     everything() ~ px(200) # Set all other columns to 200 pixels
    # ) |>
    grand_summary_rows(
      columns = mkm,
      fns = list("Total" = ~ sum(.)),
      fmt = list(~ fmt_number(.x, decimals = 1))
    ) |>
    grand_summary_rows(
      columns = pct,
      fns = list("Total" = ~ sum(.)),
      fmt = list(~ fmt_percent(.x, decimals = 2)) 
    ) |>

    tab_style(
      style = cell_fill(color = "#e6f0fa"),
      locations = cells_body(columns = pct, rows = pct > .01)
    ) |>
    tab_style(
      style = cell_fill(color = "#c5d6e9"),
      locations = cells_body(columns = pct, rows = pct > .02)
    )

  return(tbl)
}

```

```{r}
#| label: fn_build_global_map
fn_build_global_map <- function(plot_data, palette, cp) {

  p <- ggplot(plot_data) +
    geom_sf(aes(color = grp), size = 0.01) +
    scale_color_manual(values = palette, drop = FALSE) +
    geom_sf(data = coastline_sf, color = "black", linewidth = 0.1) +
    coord_sf(crs = rbn_prj) +
    guides(color = guide_legend(override.aes = list(size = 4 ))) # legend point size

  if (cp == "dcp") {
    p <- p +  
      labs(
        title = "Climate Group Classification Changes ",
        color = "New\nGroup"
      )
  } else {
    p <- p + labs(color = "Old\nGroup")
  }

  return(p)
}
```

## Analysis
### Summary
#### Summary Table
```{r}
#| label: summary_table

# summmarize crp group mkm and pct
df1 <- import_df |>
  summarize(
    mkm_c = sum(mkm),
    pct_c = sum(pct),
    .by = c(cgrp)) |>
  rename(cg = cgrp)

# summmarize dcp group mkm and pct
df2 <- import_df |>
  summarize(
    mkm_r = sum(mkm),
    pct_r = sum(pct),
    .by = c(rgrp)) |>
  rename(cg = rgrp)

# join crp and dcp and calculate difference
join_df <- df1 |> 
  inner_join(df2, by = "cg") |>
  mutate(mkm_d = mkm_r - mkm_c) |>
  mutate(pct_d = pct_r - pct_c)

# shifts from other groups
df3 <- shifts_df |>
  summarize(
    mkm_g = sum(mkm),
    pct_g = sum(pct),
    .by = c(rgrp)) |>
  rename(cg = rgrp)

# join tables
join_df <- join_df  |> 
  inner_join(df3, by = "cg")

# shifts to other groups
df4 <- shifts_df |>
  summarize(
    mkm_l = sum(mkm) * -1,
    pct_l = sum(pct) * -1,
    .by = c(cgrp)) |>
  rename(cg = cgrp)

# join tables
join_df <- join_df  |> 
    inner_join(df4, by = "cg")
    
# select columns for table to display    
tbl_df <- join_df  |> 
    select(cg,
      mkm_c, mkm_g, mkm_l, mkm_r, mkm_d,
      pct_c, pct_g, pct_l, pct_r, pct_d
    ) |> 
    mutate(across(c(pct_c, pct_g, pct_l, pct_r, pct_d), ~ .x / 100))

# create gt table
t1 <- fn_build_summary_table(tbl_df)

```

#### Summary Map
```{r}
#| label: summary_maps

# Build dcp map
plot_data <- shifts_sf |>
  select(rgrp) |>
  rename(grp = rgrp)
p1 <- fn_build_global_map (plot_data, grp_palette, "dcp")

# build crp map
plot_data <- shifts_sf |>
  select(cgrp) |>
  rename(grp = cgrp)
p2 <- fn_build_global_map (plot_data, grp_palette, "crp")

```

#### Summary Display

```{r}
#| label: summary_display
#| fig-height: 7
#| fig-aspect: .62   
#| out-width: 100%

# display table
t1

# display maps
p1 / p2
```

### Detail

#### Detail Table

```{r}
#| label: detail_table

tbl_df <- shifts_df |>
  #filter(pct >= 0.1) |>
  mutate(pct = pct / 100) |>
  arrange(cgrp, rgrp)

t1 <- fn_build_detail_table(tbl_df, "All Groups")
t1

```

#### Detail Analysis

```{r}
#| label: fn_detail_analysis

fn_detail_analysis <- function(shifts_df, shifts_sf, grp_palette, g) {

  tbl_df <- shifts_df |> 
  filter(rgrp == g) |>
  mutate(pct = pct / 100) |>
  arrange(rgrp)
  t1 <- fn_build_detail_table(tbl_df, paste("New Group ", g))

  g_new_sf <- shifts_sf |> 
  filter(rgrp == g) |>
  select(rgrp) |>
  rename(grp = rgrp)

  p1 <- fn_build_global_map(g_new_sf, grp_palette, "dcp")

  g_old_sf <- shifts_sf |> 
  filter(rgrp == g) |>
  select(cgrp) |>
  rename(grp = cgrp)

  p2 <- fn_build_global_map(g_old_sf, grp_palette, "crp")

 return(list(t1 = t1, p1 = p1, p2 = p2))

}
```

```{r}
#| label: detail_analysis
#| fig-height: 7
#| fig-aspect: .62  
#| out-width: 100%

results = fn_detail_analysis(shifts_df, shifts_sf, grp_palette, "A")
results$t1
results$p1 / results$p2

results = fn_detail_analysis(shifts_df, shifts_sf, grp_palette, "B")
results$t1
results$p1 / results$p2

results = fn_detail_analysis(shifts_df, shifts_sf, grp_palette, "C")
results$t1
results$p1 / results$p2

results = fn_detail_analysis(shifts_df, shifts_sf, grp_palette, "D")
results$t1
results$p1 / results$p2

results = fn_detail_analysis(shifts_df, shifts_sf, grp_palette, "E")
results$t1
results$p1 / results$p2
```
