---
title: "Classify Trewartha"
---

## Setup

### Packages

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ecmwfr)
  library(tidync)
  library(data.table)
  library(sf)
  library(arrow)
  library(units)

  library(gt)
  #library(gtExtras)
  #library(htmltools)

  library(RColorBrewer)
  library(viridis)
  library(scales) # for cut_number
  library(rnaturalearth)
})
```

### Climate Periods

```{r climate-periods}

# Climatological Standard Reference Period Normals
crp_beg <- 1961
crp_end <- 1990
crp_lbl <- paste("CRP ", crp_beg, "-", crp_end, sep = "")

# Climatological Period Average
rcp_beg <- 2011
rcp_end <- 2020
rcp_lbl <- paste("rcp ", rcp_beg, "-", rcp_end, sep = "")
```

### Paths

```{r paths}
dir_transform <- "_data/2-transform/"
dir_classify <- "_data/classify/"
```

```{r figures-output}
# Centralize figures created by chunks in this doc
knitr::opts_chunk$set(fig.path = "_figures/classify-")
```

### Dictionaries

```{r ktc-dictionary}

ktc_zone <- c(
    "Ar",
    "Aw",
    "BW",
    "BS",
    "Cs",
    "Cf",
    "Do",
    "Dc",
    "E",
    "Ft",
    "Fi"
  )

ktc_label <- c(
    "Ar: Tropical Wet",
    "Aw: Tropical Wet & Dry",
    "BW: Desert",
    "BS: Steppe",
    "Cs: Mediterranean",
    "Cf: Subtropical",
    "Do: Temperate Oceanic",
    "Dc: Temperate Continental",
    "E:  Sub-Arctic",
    "Ft: Polar Tundra",
    "Fi: Polar Ice Cap"
  )

ktc_dict  <- data.frame(zone= ktc_zone, label=ktc_label)
```

```{r kcc-dictionary}

kcc_zone <- c(
    "Af",
    "Am",
    "As",
    "Aw",
    "BSh",
    "BSk",
    "BWh",
    "BWk",
    "Cfa",
    "Cfb",
    "Cfc",
    "Csa",
    "Csb",
    "Csc",
    "Cwa",
    "Cwb",
    "Cwc",
    "Dfa",
    "Dfb",
    "Dfc",
    "Dfd",
    "Dsa",
    "Dsb",
    "Dsc",
    "Dsd",
    "Dwa",
    "Dwb",
    "Dwc",
    "Dwd",
    "ET",
    "EF"
  )


```

### Palettes

```{r ktc palette}

 ktc_color <- c(
    "#040ff0",
    "#0474fb",
    "#ffe505",
    "#ff9005",
    "#0eff00",
    "#2db83d",
    "#b64dff",
    "#7c00ff",
    "#017783",
    "#72b8ce",
    "#b4dfe3"
  )

ktc_palette  <- data.frame(zone= ktc_zone, color=ktc_color)

```

### Map Projections

```{r}
rbn_prj <- "ESRI:54030"
```

### Read transformed climate period data

```{r read-transformed-data}

typ <- "crp"

pth <- paste(dir_transform, typ, "-nc-summary.csv", sep = "")
crp_nc_summary_df <- read_csv(pth, show_col_types = FALSE) 

pth <- paste(dir_transform, typ, "-monthly-data-t.parquet", sep = "")
crp_t_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-monthly-data-p.parquet", sep = "")
crp_p_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-t.parquet", sep = "")
crp_t_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-p.parquet", sep = "")
crp_p_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-period-average.parquet", sep = "")
crp_cn_df <- read_parquet(pth) 

typ <- "rcp"

pth <- paste(dir_transform, typ, "-nc-summary.csv", sep = "")
crp_nc_summary_df <- read_csv(pth, show_col_types = FALSE) 

pth <- paste(dir_transform, typ, "-monthly-data-t.parquet", sep = "")
rcp_t_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-monthly-data-p.parquet", sep = "")
rcp_p_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-t.parquet", sep = "")
rcp_t_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-average-stats-p.parquet", sep = "")
rcp_p_stats_df <- read_parquet(pth) 
pth <- paste(dir_transform, typ, "-period-average.parquet", sep = "")
rcp_cn_df <- read_parquet(pth) 

```

## Classification

### KTC classification function

```{r classify_ktc}
fn_classify_ktc <- function(df) {

# Step 1: Add seasonal precip stats (Summer/Winter) based on hemisphere
#         Summer: high sun 6 months (SH: Oct–Mar, NH: Apr–Sep)
#         Winter: low  sun 6 months (NH: Oct–Mar, SH: Apr–Sep)
  df <- df |>
    mutate(
      pST = case_when(lat >= 0 ~ pats, TRUE ~ potm),
      pWT = case_when(lat >= 0 ~ potm, TRUE ~ pats),
      pMnST = case_when(lat >= 0 ~ pmna, TRUE ~ pmno),
      pMxST = case_when(lat >= 0 ~ pmxa, TRUE ~ pmxo),
      pMnWT = case_when(lat >= 0 ~ pmno, TRUE ~ pmna),
      pMxWT = case_when(lat >= 0 ~ pmxo, TRUE ~ pmxa)
    )

# Step 2: Calculate Aridity threshold
  df <- df |>
    mutate(
      athr = case_when(
        ptot != 0 ~ (10 * (tavg - 10)) + (3 * (pST / ptot) * 100),
        TRUE ~ 10 * (tavg - 10)
      )
    )

# Step 3: Assign Primary Group
  df <- df |>
    mutate(
      z1 = case_when(
        tmax < 10 ~ "F",
        ptot < (athr * 2) ~ "B",
        tmin >= 18 ~ "A",
        tg10 >= 8 ~ "C",
        tg10 >= 4 ~ "D",
        tg10 >= 1 ~ "E",
        TRUE ~ "X"
      ),
      zn = ""
    )

# Step 4: Assign secondary group
  df <- df |>
    mutate(
      z2 = case_when(
        z1 == "A" & pl60 <= 2 ~ "r",
        z1 == "A" ~ "w",
        z1 == "B" & ptot < athr ~ "W",
        z1 == "B" ~ "S",
        z1 == "C" & pWT >= pST * 3 & pmin < 30 & ptot < 890 ~ "s",
        z1 == "C" ~ "f",
        z1 == "D" & tmin > 0 ~ "o",
        z1 == "D" ~ "c",
        z1 == "F" & tmax > 0 ~ "t",
        z1 == "F" ~ "i",
        TRUE ~ ""
      ),
      zn = paste(z1, z2, sep = "")
    )
  return(df)
}
```

### Classify climate periods using KTC

```{r ktc-crp-zones}

ktc_crp_cn_df <- fn_classify_ktc(crp_cn_df)
ktc_crp_cn_df <- ktc_crp_cn_df |> select(lon, lat, zn, area, lsm)
ktc_crp_cn_sf <- st_as_sf(ktc_crp_cn_df, coords = c("lon", "lat"), crs = 4326)

ktc_d_df <- fn_classify_ktc(rcp_cn_df)
ktc_d_df <- ktc_d_df |> select(lon, lat, zn, area, lsm)
ktc_d_sf <- st_as_sf(ktc_d_df, coords = c("lon", "lat"), crs = 4326)

# combine areas by crp and rcp

ktc_cd_sf <- ktc_crp_cn_sf
ktc_cd_sf <- ktc_cd_sf |> rename(czn = zn)
ktc_cd_sf$dzn <- ktc_d_sf$zn

ktc_grp_geom_sf <- ktc_cd_sf |>
  filter(lsm==1) |>
  summarise(
    geometry = st_combine(geometry),
    mkm = sum(area),
    .by = c(czn, dzn)
  ) |>
  mutate(cz1 = substr(czn, 1, 1)) |>
  mutate(dz1 = substr(dzn, 1, 1)) |>
  mutate(pct = round(mkm / sum(mkm) * 100, 3)) |>
  select(czn, cz1, dzn, dz1, mkm, pct, geometry) |>
  arrange(czn, dzn)
ktc_grp_geom_sf <- st_set_crs(ktc_grp_geom_sf, 4326)

```

## Summary

### KTC summary

```{r build-ktc-summary}

# Build CRP and rcp aggregates from grouped land geometries
ktc_crp_df <- ktc_grp_geom_sf |>
  st_drop_geometry() |>
  select(czn, cz1, mkm, pct) |>
  summarize(mkm = sum(mkm), pct = sum(pct), .by = c(czn, cz1)) |>
  mutate(period = "crp") |>
  rename(zone = czn, z1 = cz1) |>
  arrange(zone)

ktc_rcp_df <- ktc_grp_geom_sf |>
  st_drop_geometry() |>
  select(dzn, dz1, mkm, pct) |>
  summarize(mkm = sum(mkm), pct = sum(pct), .by = c(dzn, dz1)) |>
  mutate(period = "rcp") |>
  rename(zone = dzn, z1 = dz1) |>
  arrange(zone)

# Side-by-side comparison + deltas
ktc_diff_df <- ktc_crp_df |>
  select(zone, mkm, pct) |>
  rename(cmkm = mkm, cpct = pct)

ktc_diff_df$dmkm <- ktc_rcp_df$mkm
ktc_diff_df$dpct <- ktc_rcp_df$pct

ktc_diff_df <- ktc_diff_df |>
  mutate(
    xmkm = dmkm - cmkm,
    xpct = round(dpct - cpct, 2)
  ) |>
  select(zone, cmkm, dmkm, xmkm, cpct, dpct, xpct)

# ktc_diff_df <- ktc_diff_df |>
#   left_join(ktc_dict, by = "zone") |>
#   select(label, cmkm, dmkm, xmkm, cpct, dpct, xpct)

ktc_diff_gt <- ktc_diff_df |> gt(rowname_col = "zone")

```

```{r display-ktc-summary}

ktc_tbl1 <- ktc_diff_gt |>
  tab_header(
    title = "Summary of Trewartha Climate Classification Changes",
    #subtitle = paste(crp_lbl, "vs", rcp_lbl)
  ) |>
  tab_spanner(
    label = "Area (Mkm²)",
    columns = c(cmkm, dmkm, xmkm)
  ) |>
  tab_spanner(
    label = "Earth Land Area %",
    columns = c(cpct, dpct, xpct)
  ) |>
  cols_label(
    cmkm = "CRP",
    dmkm = "rcp",
    xmkm = "Chg",
    cpct = "CRP",
    dpct = "rcp",
    xpct = "Chg"
  ) |>
  fmt_number(columns = c(cmkm, dmkm, xmkm), decimals = 1) |>
  fmt_number(columns = c(cpct, dpct, xpct), decimals = 2) |>
  grand_summary_rows(
    columns = c(cmkm, dmkm, xmkm, cpct, dpct, xpct),
    fns = list("Total" = ~ sum(.)),
    fmt = list(~ fmt_number(.x, decimals = 2))
  ) |>
  tab_footnote(
    footnote = paste("CRP: Climate Reference Period ", crp_beg, "-", crp_end, sep = ""),
    locations = cells_column_labels(columns = c(cmkm, cpct))
  ) |>
  tab_footnote(
    footnote = paste("RCP: Recent Climate Period ", rcp_beg, "-", rcp_end, sep = ""),
    locations = cells_column_labels(columns = c(dmkm, dpct))
  )

ktc_tbl1 
```


## Visualization


```{r read-coastline}
dir <- dir_transform
fil <- "ne-coastline.gpkg"
pth <- paste(dir, fil, sep = "")
coastline_sf <- st_read(pth, quiet=TRUE)
```

### Map 1

```{r map-1}

plot_data <- ktc_grp_geom_sf |>
  select(czn) |>
  rename(zone = czn)

p2 <- ggplot(plot_data) +
  geom_sf(aes(color = zone), size = 0.1) +
  scale_color_manual(
    values = setNames(ktc_palette$color, ktc_palette$zone),
    labels = setNames(ktc_dict$zone, ktc_dict$zone)
  ) +
  geom_sf(
    data = coastline_sf,
    color = "darkgrey",
    linewidth = 0.1
  ) +
  coord_sf(crs = rbn_prj) +
  labs(
    title = "Köppen-Trewartha Climate Classification",
    subtitle = crp_lbl,
    color = "Zones"
  ) +
  guides(
    color = guide_legend(
      override.aes = list(
        size = 3 # legend point size only
      )
    )
  )

```


```{r}
#| label: fig:ktc-crp-classification
#| fig-cap: "Trewartha classification (1961–1990)."
p2
```